"""empty message

Revision ID: 783937e786d8
Revises: 020160529405
Create Date: 2024-08-01 21:29:06.162223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783937e786d8'
down_revision = '020160529405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_student',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('is_instructor',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('is_instructor',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('is_student',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
